language: objective-c
osx_image: xcode10.1
script:
  - xcodebuild -scheme ARCarMovement -workspace ARCarMovement.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=11.4' build test